[theme]
primaryColor = "#001F3F"  # Azul oscuro para elementos principales
backgroundColor = "#E6E6E6"  # Gris mediano para el fondo principal
secondaryBackgroundColor = "#D3D3D3"  # Gris un poco más claro para elementos secundarios
textColor = "#001F3F"  # Azul oscuro para textos
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false